### ISSUE TITLE
Allow attributes to be set on generated style tag for CSP

### ISSUE THREAD

**Issue by crisbeto** [GoogleChromeLabs/critters#119]
Inline styles aren't compatible with the [`style-src` directive of CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src). It can be opted into, but that can introduce a security vulnerability since it allows all inline styles. One way to make it work is to set the `nonce` attribute on the stylesheet to an expression that is replaced by the nonce by the server when the stylesheet is served, e.g. `<style nonce="{% nonce %}">/* styles go here */</style>`. Currently this isn't possible, because Critters doesn't allow for attributes to be added to the `style` tag.

**Comment by kara** [comment]
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.
