### ISSUE TITLE
Crashing due to Critters.prototype.readFile vs. this$1.fs

### ISSUE THREAD

**Issue by neutraali** [GoogleChromeLabs/critters#7]
Using `new Critters()` without (in the usual Webpack plugins array) any options causes the compilation process to crash:

```
ERROR in TypeError: Cannot read property 'readFile' of undefined
  - critters.js:216 
    [LianaUI]/[critters-webpack-plugin]/dist/critters.js:216:19
 . . .
  - critters.js:215 Critters.readFile
    [LianaUI]/[critters-webpack-plugin]/dist/critters.js:215:12
  
  - critters.js:272 Critters.<anonymous>
    [LianaUI]/[critters-webpack-plugin]/dist/critters.js:272:25
. . .
  - critters.js:258 Critters.embedLinkedStylesheet
    [LianaUI]/[critters-webpack-plugin]/dist/critters.js:258:12
  
  - critters.js:233 
    [LianaUI]/[critters-webpack-plugin]/dist/critters.js:233:83
. . .
```

^ Seems to break on `Critters.prototype.readFile = function readFile(filename, encoding) {...}` because `this$1.fs` is undefined.

Tried with:
```
"html-webpack-plugin": "3.2.0"
"webpack": "4.12.0"
"webpack-dev-server": "3.1.4"
"critters-webpack-plugin": "1.0.0"
```

**Comment by developit** [comment]
Can you check if this still happens in `critters@1.1.0`?

**Comment by isidrok** [comment]
I was having the same error because a css file I was loading in the html entrypoint could not be found (404), removing that link fixed the problem.

**Comment by vinaybedre** [comment]
I am using Vue CLI 3 with Vuetify and have the same issue. Vuetify uses stylus and all the files referred are included. Can a repo help you guys solve?

**Comment by isidrok** [comment]
Hi @DavidCondit, I was having that problem because there seems to be a conflict when using `mini-css-extract-plugin` and `prerender-loader`. `prerender-loader` was outputing incorrect hashes for the css files which could not be resolved later by `Critters` but using `contenthash` did work.

Here is my relevant configuration:

```js
const HASH = 'contenthash';
{
entry: resolve('src/index.js'),
output: {
  filename: `static/js/[name]${HASH}.js`,
  chunkFilename: `static/js/[name]${HASH}.js`,
  path: resolve('dist'),
  publicPath: '/',
  },
plugins: [
  new webpack.HashedModuleIdsPlugin(),
  new MiniCssExtractPlugin({
    filename: `static/css/[name]${HASH}.css`,
    chunkFilename: `static/css/[name]${HASH}.css`,
  }),
 new HtmlWebpackPlugin({
    template: `!prerender-loader?string!${resolve('public/index.html')}`,
    minify: {
      removeComments: true,
      collapseWhitespace: true,
      removeRedundantAttributes: true,
      useShortDoctype: true,
      removeEmptyAttributes: true,
      removeStyleLinkTypeAttributes: false,
      keepClosingSlash: true,
      minifyURLs: true,
    },
  }),
  new Critters(),
}
```

Will try to reproduce that `prerender-loader` behaviour with a minimal example and open an issue in that repo.

**Comment by developit** [comment]
@isidrok hmm - prerender-loader probably can't generate the same hashes for CSS as the main bundle. 

The simple fix here would be to have `this.fs` fall back to `require('fs')`, but I don't think that will work properly when running Webpack against a virtual filesystem.

**Comment by isidrok** [comment]
Hi @developit, I can confirm that the issue is due to `prerender-loader` outputing incorrect hashes for css files loaded with `mini-css-extract-plugin` for `dynamic chunks` if the hashing strategy is different from `contenthash`.

Then `Critters` fails because the file cannot be found.

The reproduction is in https://github.com/isidrok/prerender-loader-reprod, the steps are in the readme.

I'll open an issue in prerender-loader later.

**Comment by developit** [comment]
@MikaAK @isidrok - it looks like `mini-css-extract-plugin` had a bug that caused the hashes to be dependent on things other than the filename:
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/281

Updating to the latest version fixes this in my projects, hope it does for you too.

**Comment by MikaAK** [comment]
That did the trick!
